name: Assertions and static report

on:
  # push:
  #   branches:
  #     - main
  # Running on main is since the site is not yet live
  workflow_dispatch:
  schedule:
    - cron: 0 7 * * 1/3 # Every Monday and Thursday at 7am UTC

jobs:
  assertions-and-static-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site esteban-soubiran.site --budget 75 --build-static

      - run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
